### ISSUE TITLE
很棒的项目，希望能参加开发！

### ISSUE THREAD

**Issue by yk17310320725** [together08/EasyPasswall#1]
很棒的项目，正好最近有在 Linux 终端使用代理的需求。找了很多都是 GUI 界面，并不满足我的需求，所以看到该项目很是激动，但看到该项目还未完善，激动的心顿时就凉下来了。

个人希望能够使用 v2ray 协议的订阅链接，正常的在终端中使用代理。

正好我会一点 python 和 shell，也许可以和作者一起结对编程。

不过我目前展示不太了解代理方面的知识，希望作者可以给我一些资料参考。

**Comment by together08** [comment]
刚刚邮箱查找东西偶然看见的（

emm，这个其实算是疫情期间无聊做的。

后来就没动过了……

如果你想和我一起来搞这个，那么我就把你加进 collaborators 里面。

代理方面的知识……说真的，我其实也不是很了解……

我也就只是参照一下现有的 GUI 程序，比如 V2rayN 之类的。

我以前在 Linux Shell 下用 V2ray 代理，基本都是 WIndows 下 V2rayN 配置完成把配置文件传上服务器，直接让 V2ray 可执行文件执行这个的。

其实吧，Shell 在这里其实并不是很必要，我更新后会删掉，因为之前写的时候不知道可以 Pyinstaller 打包可执行文件……

总之，咕了这么久的一个项目被人翻出来，内心也是很激动的。

对了，如果方便，可以把你的 QQ/TG 或者别的什么联系方式发到我的邮箱（Issues 不方便交流）。

感谢支持！

**Comment by yk17310320725** [comment]
不好意思，今天才看到。我的 QQ 号已经发送到你的邮箱里了。

**Comment by yk17310320725** [comment]
另外，我这几天也研究了在命令行使用代理。于是发现了 [v2sub](https://github.com/ThomasZN/v2sub) 这个工具。但，我并没有成功的使用这个工具。

另外 v2ray 的 [文档](https://www.v2fly.org/) 是非常不错的入门资料。
